Add id to linting

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -10,8 +10,118 @@ env:
   bashEnd: \033[0m
 
 jobs:
-  format-check:
+  linting:
     runs-on: ubuntu-latest
+
+    steps:
+      - name: Clone the repo
+        uses: actions/checkout@v3
+
+      - name: Install clang-tidy
+        run: |
+          sudo apt-get install -y clang-tidy fd-find
+          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
+          export PATH="$PATH:$GITHUB_ACTION_PATH"
+
+          # Check that the commands installed correctly
+          fdfind --version
+          echo -e "::endgroup::"
+          
+          echo -e "${{ env.bashInfo }} Using clang-tidy version "$(clang-tidy --version)" ${{ env.bashEnd }}"
+
+      - name: Linting
+        id: action-linting
+        run: |
+          # Parse the optional inputs
+          args=""
+          
+          # Get all .cpp and .hpp files, as well as any other requested file types.
+          # Then run cppcheck.
+          fdfind -e cpp -e hpp ${args} --exec clang-tidy {} --config-file=.clang-tidy --checks=* \
+          --warnings-as-errors --fix --fix-errors \;
+          
+          # Determine if there was a linting diff.
+          # If there was, create a patch of it.
+          set +e
+          git diff --exit-code >> lintChanges.patch
+          exitCode=$?
+          set -e
+
+          if [ $exitCode -eq 0 ]; then
+              echo -e "::endgroup::"
+              # echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          else
+              # Run a git diff to print the linting differences
+              echo -e "::group::${{ env.bashInfo }} Linting Difference ${{ env.bashEnd }}"
+              git diff --color=always
+              echo -e "::endgroup::"
+              echo -e "${{ env.bashFail }} List of files with linting errors: ${{ env.bashEnd }}"
+              echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
+              # echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
+          fi
+          exit $exitCode
+
+      - name: Upload Git Patch
+        if: failure() && ( steps.action-linting.outcome == 'failure' )
+        id: upload-linting-patch
+        uses: actions/upload-artifact@v3
+        with:
+          name: lintingChanges
+          path: ${{ inputs.path }}/lintingChanges.patch
+          retention-days: 7
+
+  analysis:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Clone the repo
+        uses: actions/checkout@v3
+
+      - name: Install cppcheck
+        run: |
+          sudo apt-get install -y cppcheck fd-find
+          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
+          export PATH="$PATH:$GITHUB_ACTION_PATH"
+
+          # Check that the commands installed correctly
+          fdfind --version
+          echo -e "::endgroup::"
+          
+          echo -e "${{ env.bashInfo }} Using cppcheck version "$(cppcheck --version)" ${{ env.bashEnd }}"
+
+      - name: Configure project
+        run: >
+          cmake -B build
+          -DCMAKE_CXX_COMPILER=g++
+          -DCMAKE_BUILD_TYPE=Debug
+          -S ${{ github.workspace }}
+
+      - name: Perform analysis
+        run: |
+          # Parse the optional inputs
+          args=""
+          
+          # Get all .cpp and .hpp files, as well as any other requested file types.
+          target_files="$(fdfind -e cpp -e hpp ${args})"
+          
+          # Then run cppcheck.
+          cppcheck --enable=all --inconclusive --std=c++17 --suppress=missingIncludeSystem \
+          -i build -I nucleus/include -I nucleus/src -I nucleus/tests \
+          -I build/_deps/device-sdk-cpp-src/crt/aws-crt-cpp/include -I build/_deps/catch2-src/src \
+          --verbose --xml $(echo $target_files) 2> report.xml \;
+
+      - name: Generate report
+        run: >
+          cppcheck-htmlreport --file=report.xml --report-dir=cppcheck_report
+
+      - name: Upload report
+        uses: actions/upload-artifact@v3
+        with:
+          name: cppcheck_report
+          path: cppcheck_report
+
+  format-check:
+    runs-on: ubuntu-20.04
     steps:
       - name: Clone the repo
         uses: actions/checkout@v3
@@ -29,7 +139,7 @@ jobs:
           echo -e "::endgroup::"
 
           # echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          echo -e "${{ env.bashInfo }} Using clang-format Version "$(clang-format --version)" ${{ env.bashEnd }}"
+          echo -e "${{ env.bashInfo }} Using clang-format version "$(clang-format --version)" ${{ env.bashEnd }}"
 
       - name: Check Formatting
         id: action-formatting-check
@@ -89,110 +199,3 @@ jobs:
           name: formattingChanges
           path: ${{ inputs.path }}/formattingChanges.patch
           retention-days: 5
-
-  linting:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Clone the repo
-        uses: actions/checkout@v3
-
-      - name: Install clang-tidy
-        run: |
-          sudo apt-get install -y clang-tidy fd-find
-          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
-          export PATH="$PATH:$GITHUB_ACTION_PATH"
-
-          # Check that the commands installed correctly
-          fdfind --version
-          echo -e "::endgroup::"
-          clang-tidy --version
-          clang-tidy --help
-
-      - name: Linting
-        run: |
-          # Parse the optional inputs
-          args=""
-          
-          # Get all .cpp and .hpp files, as well as any other requested file types.
-          # Then run cppcheck.
-          fdfind -e cpp -e hpp ${args} --exec clang-tidy {} --config-file=.clang-tidy --checks=* \
-          --warnings-as-errors --fix --fix-errors \;
-          
-          # Determine if there was a linting diff.
-          # If there was, create a patch of it.
-          set +e
-          git diff --exit-code >> lintChanges.patch
-          exitCode=$?
-          set -e
-
-          if [ $exitCode -eq 0 ]; then
-              echo -e "::endgroup::"
-              # echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          else
-              # Run a git diff to print the linting differences
-              echo -e "::group::${{ env.bashInfo }} Linting Difference ${{ env.bashEnd }}"
-              git diff --color=always
-              echo -e "::endgroup::"
-              echo -e "${{ env.bashFail }} List of files with linting errors: ${{ env.bashEnd }}"
-              echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
-              # echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
-          fi
-          exit $exitCode
-
-      - name: Upload Git Patch
-        if: failure() && ( steps.linting.outcome == 'failure' )
-        id: upload-linting-patch
-        uses: actions/upload-artifact@v3
-        with:
-          name: lintingChanges
-          path: ${{ inputs.path }}/lintingChanges.patch
-          retention-days: 7
-
-  analysis:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Clone the repo
-        uses: actions/checkout@v3
-
-      - name: Install cppcheck
-        run: |
-          sudo apt-get install -y cppcheck fd-find
-          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
-          export PATH="$PATH:$GITHUB_ACTION_PATH"
-
-          # Check that the commands installed correctly
-          fdfind --version
-          echo -e "::endgroup::"
-
-      - name: Configure project
-        run: >
-          cmake -B build
-          -DCMAKE_CXX_COMPILER=g++
-          -DCMAKE_BUILD_TYPE=Debug
-          -S ${{ github.workspace }}
-
-      - name: Perform analysis
-        run: |
-          # Parse the optional inputs
-          args=""
-          
-          # Get all .cpp and .hpp files, as well as any other requested file types.
-          target_files="$(fdfind -e cpp -e hpp ${args})"
-          
-          # Then run cppcheck.
-          cppcheck --enable=all --inconclusive --std=c++17 --suppress=missingIncludeSystem \
-          -i build -I nucleus/include -I nucleus/src -I nucleus/tests \
-          -I build/_deps/device-sdk-cpp-src/crt/aws-crt-cpp/include -I build/_deps/catch2-src/src \
-          --verbose --xml $(echo $target_files) 2> report.xml \;
-
-      - name: Generate report
-        run: >
-          cppcheck-htmlreport --file=report.xml --report-dir=cppcheck_report
-
-      - name: Upload report
-        uses: actions/upload-artifact@v3
-        with:
-          name: cppcheck_report
-          path: cppcheck_report
